title: "Susana Nunes"
url: "https://susanapnunes.github.io/"
baseurl: "./"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: UA-104489558-5

favicon: true
favicon_location: favicon.ico

footer: true
footer_url: "https://github.com/SusanaPNunes"
footer_text: ""

sass:
    style: compressed
    sass_dir: _sass


